### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by dpoulopoulos** [IliasPap/COVIDNet#1]
Hi, great work! In the paper, the authors say that they pre-trained the model on ImageNet. Were you able to do that? I see that you report an accuracy >90% on the notebook. Did you achieve that without ImageNet pre-training?

**Comment by IliasPap** [comment]
The total test accuracy is >90% but the results in Covid class are much worse . That's why pre training on ImageNet is required.
I'm testing some classic CNN architectures today and i will commit the results

Αποκτήστε το Outlook για Android<https://aka.ms/ghei36>
________________________________

**Comment by AasiaRehman** [comment]
Can I run this code on CPU?

**Comment by IliasPap** [comment]
@AasiaRehman  Yes but the training will last longer

**Comment by AasiaRehman** [comment]
But it is showing me error of CUDA out of memory
What is this error about

With Regards
Aasia Rehman

**Comment by IliasPap** [comment]
@AasiaRehman  If you initialize the " --cuda " argument as False it shouln't show this error since you are not using the gpu
