### ISSUE TITLE
Issues on dataset preparation

### ISSUE THREAD

**Issue by ZhenyF** [IliasPap/COVIDNet#3]
Hi,
Thanks for the work!
I am trying to generate the dataset using the code in COVIDNet.ipynb:
1. `git clone https://github.com/IliasPap/COVID-Net.git
` seems not exist, so I modified that to `git clone https://github.com/IliasPap/COVIDNet.git
`. Is that correct?
2. I cannot find the .npy file in the line `'/content/COVID-Net/rsna_test_patients_{}.npy'.format(key)` 

Could you please help with this?
Many thanks!

**Comment by IliasPap** [comment]
Thanks for the comment, I have updated the notebook and uploaded the npy file.
Check the new commit 👍

**Comment by ZhenyF** [comment]
Cheers!
